### ISSUE TITLE
Pluralsight licences

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-prod/ICES-IT#1]
Nas to check if MSDN users get a rebate and report to Marianne

**Comment by Neldeberg** [comment]
I have now places an order for 14 Pluralsight licenses through MSec

**Comment by Nas-ICES-IT** [comment]
@Neldeberg Ok. But with MSDN benefit with enterprise it also can be 1 year free .... 

6 Months for everyone... https://www.pluralsight.com/partners/microsoft/visual-studio-enterprise?aid=701j0000002BK6yAAG&oid=&promo=&utm_campaign=&utm_content=&utm_medium=partner_partner_web_referral&utm_source=&utm_term=
